on:
  push:
    branches:
      - main

name: 🚀 Deploy website on push 1

jobs:
  web-deploy:
    name: 🎉 Deploy website
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
      - name: 📂 Sync via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.swift.org.ng
          username: root@swift.org.ng
          password: 6%w%DiLY6J,v
